# Generated by Django 6.0.6 on 2026-06-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('apellido', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('clave', models.TextField()),
                ('telefono', models.TextField(blank=True, null=True)),
                ('rol', models.TextField()),
                ('activo', models.BooleanField()),
                ('tokenactivacion', models.TextField(blank=True, null=True, unique=True)),
                ('estado', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
